INSERT INTO Paises VALUES ("Afganistán");
INSERT INTO Paises VALUES ("Albania");
INSERT INTO Paises VALUES ("Alemania");
INSERT INTO Paises VALUES ("Andorra");
INSERT INTO Paises VALUES ("Angola");
INSERT INTO Paises VALUES ("Antigua y Barbuda");
INSERT INTO Paises VALUES ("Arabia Saudí");
INSERT INTO Paises VALUES ("Argelia");
INSERT INTO Paises VALUES ("Argentina");
INSERT INTO Paises VALUES ("Armenia");
INSERT INTO Paises VALUES ("Australia");
INSERT INTO Paises VALUES ("Austria");
INSERT INTO Paises VALUES ("Azerbaiyán");
INSERT INTO Paises VALUES ("Bahamas");
INSERT INTO Paises VALUES ("Bangladés");
INSERT INTO Paises VALUES ("Barbados");
INSERT INTO Paises VALUES ("Baréin");
INSERT INTO Paises VALUES ("Bélgica");
INSERT INTO Paises VALUES ("Belice");
INSERT INTO Paises VALUES ("Benín");
INSERT INTO Paises VALUES ("Bielorrusia");
INSERT INTO Paises VALUES ("Birmania");
INSERT INTO Paises VALUES ("Bolivia");
INSERT INTO Paises VALUES ("Bosnia-Herzegovina");
INSERT INTO Paises VALUES ("Botsuana");
INSERT INTO Paises VALUES ("Brasil");
INSERT INTO Paises VALUES ("Brunéi");
INSERT INTO Paises VALUES ("Bulgaria");
INSERT INTO Paises VALUES ("Burkina Faso");
INSERT INTO Paises VALUES ("Burundi");
INSERT INTO Paises VALUES ("Bután");
INSERT INTO Paises VALUES ("Cabo Verde");
INSERT INTO Paises VALUES ("Camboya");
INSERT INTO Paises VALUES ("Camerún");
INSERT INTO Paises VALUES ("Canadá");
INSERT INTO Paises VALUES ("Catar");
INSERT INTO Paises VALUES ("República Centroafricana");
INSERT INTO Paises VALUES ("Chad");
INSERT INTO Paises VALUES ("República Checa");
INSERT INTO Paises VALUES ("Chile");
INSERT INTO Paises VALUES ("China");
INSERT INTO Paises VALUES ("Chipre");
INSERT INTO Paises VALUES ("Colombia");
INSERT INTO Paises VALUES ("Comoras");
INSERT INTO Paises VALUES ("República del Congo");
INSERT INTO Paises VALUES ("República Democrática del Congo");
INSERT INTO Paises VALUES ("Corea del Norte");
INSERT INTO Paises VALUES ("Corea del Sur");
INSERT INTO Paises VALUES ("Costa de Marfil");
INSERT INTO Paises VALUES ("Costa Rica");
INSERT INTO Paises VALUES ("Croacia");
INSERT INTO Paises VALUES ("Cuba");
INSERT INTO Paises VALUES ("Dinamarca");
INSERT INTO Paises VALUES ("Dominica");
INSERT INTO Paises VALUES ("República Dominicana");
INSERT INTO Paises VALUES ("Ecuador");
INSERT INTO Paises VALUES ("Egipto");
INSERT INTO Paises VALUES ("El Salvador");
INSERT INTO Paises VALUES ("Emiratos Árabes Unidos");
INSERT INTO Paises VALUES ("Eritrea");
INSERT INTO Paises VALUES ("Eslovaquia");
INSERT INTO Paises VALUES ("Eslovenia");
INSERT INTO Paises VALUES ("España");
INSERT INTO Paises VALUES ("Estados Unidos");
INSERT INTO Paises VALUES ("Estonia");
INSERT INTO Paises VALUES ("Etiopía");
INSERT INTO Paises VALUES ("Filipinas");
INSERT INTO Paises VALUES ("Finlandia");
INSERT INTO Paises VALUES ("Fiyi");
INSERT INTO Paises VALUES ("Francia");
INSERT INTO Paises VALUES ("Gabón");
INSERT INTO Paises VALUES ("Gambia");
INSERT INTO Paises VALUES ("Georgia");
INSERT INTO Paises VALUES ("Ghana");
INSERT INTO Paises VALUES ("Granada");
INSERT INTO Paises VALUES ("Grecia");
INSERT INTO Paises VALUES ("Guatemala");
INSERT INTO Paises VALUES ("Guinea");
INSERT INTO Paises VALUES ("Guinea-Bisáu");
INSERT INTO Paises VALUES ("Guinea Ecuatorial");
INSERT INTO Paises VALUES ("Guyana");
INSERT INTO Paises VALUES ("Haití");
INSERT INTO Paises VALUES ("Honduras");
INSERT INTO Paises VALUES ("Hungría");
INSERT INTO Paises VALUES ("India");
INSERT INTO Paises VALUES ("Indonesia");
INSERT INTO Paises VALUES ("Irak");
INSERT INTO Paises VALUES ("Irán");
INSERT INTO Paises VALUES ("Irlanda");
INSERT INTO Paises VALUES ("Islandia");
INSERT INTO Paises VALUES ("Israel");
INSERT INTO Paises VALUES ("Italia");
INSERT INTO Paises VALUES ("Jamaica");
INSERT INTO Paises VALUES ("Japón");
INSERT INTO Paises VALUES ("Jordania");
INSERT INTO Paises VALUES ("Kazajistán");
INSERT INTO Paises VALUES ("Kenia");
INSERT INTO Paises VALUES ("Kirguistán");
INSERT INTO Paises VALUES ("Kiribati");
INSERT INTO Paises VALUES ("Kuwait");
INSERT INTO Paises VALUES ("Laos");
INSERT INTO Paises VALUES ("Lesoto");
INSERT INTO Paises VALUES ("Letonia");
INSERT INTO Paises VALUES ("Líbano");
INSERT INTO Paises VALUES ("Liberia");
INSERT INTO Paises VALUES ("Libia");
INSERT INTO Paises VALUES ("Liechtenstein");
INSERT INTO Paises VALUES ("Lituania");
INSERT INTO Paises VALUES ("Luxemburgo");
INSERT INTO Paises VALUES ("Macedonia del Norte");
INSERT INTO Paises VALUES ("Madagascar");
INSERT INTO Paises VALUES ("Malasia");
INSERT INTO Paises VALUES ("Malaui");
INSERT INTO Paises VALUES ("Maldivas");
INSERT INTO Paises VALUES ("Mali");
INSERT INTO Paises VALUES ("Malta");
INSERT INTO Paises VALUES ("Marruecos");
INSERT INTO Paises VALUES ("Islas Marshall");
INSERT INTO Paises VALUES ("Mauricio");
INSERT INTO Paises VALUES ("Mauritania");
INSERT INTO Paises VALUES ("México");
INSERT INTO Paises VALUES ("Micronesia");
INSERT INTO Paises VALUES ("Moldavia");
INSERT INTO Paises VALUES ("Mónaco");
INSERT INTO Paises VALUES ("Mongolia");
INSERT INTO Paises VALUES ("Montenegro");
INSERT INTO Paises VALUES ("Mozambique");
INSERT INTO Paises VALUES ("Namibia");
INSERT INTO Paises VALUES ("Nauru");
INSERT INTO Paises VALUES ("Nepal");
INSERT INTO Paises VALUES ("Nicaragua");
INSERT INTO Paises VALUES ("Níger");
INSERT INTO Paises VALUES ("Nigeria");
INSERT INTO Paises VALUES ("Noruega");
INSERT INTO Paises VALUES ("Nueva Zelanda");
INSERT INTO Paises VALUES ("Omán");
INSERT INTO Paises VALUES ("Países Bajos");
INSERT INTO Paises VALUES ("Pakistán");
INSERT INTO Paises VALUES ("Palaos");
INSERT INTO Paises VALUES ("Palestina");
INSERT INTO Paises VALUES ("Panamá");
INSERT INTO Paises VALUES ("Papúa Nueva Guinea");
INSERT INTO Paises VALUES ("Paraguay");
INSERT INTO Paises VALUES ("Perú");
INSERT INTO Paises VALUES ("Polonia");
INSERT INTO Paises VALUES ("Portugal");
INSERT INTO Paises VALUES ("Reino Unido");
INSERT INTO Paises VALUES ("Ruanda");
INSERT INTO Paises VALUES ("Rumanía");
INSERT INTO Paises VALUES ("Rusia");
INSERT INTO Paises VALUES ("Islas Salomón");
INSERT INTO Paises VALUES ("Samoa");
INSERT INTO Paises VALUES ("San Cristóbal y Nieves");
INSERT INTO Paises VALUES ("San Marino");
INSERT INTO Paises VALUES ("San Vicente y las Granadinas");
INSERT INTO Paises VALUES ("Santa Lucía");
INSERT INTO Paises VALUES ("Santo Tomé y Príncipe");
INSERT INTO Paises VALUES ("Senegal");
INSERT INTO Paises VALUES ("Serbia");
INSERT INTO Paises VALUES ("Seychelles");
INSERT INTO Paises VALUES ("Sierra Leona");
INSERT INTO Paises VALUES ("Singapur");
INSERT INTO Paises VALUES ("Siria");
INSERT INTO Paises VALUES ("Somalia");
INSERT INTO Paises VALUES ("Sri Lanka");
INSERT INTO Paises VALUES ("Suazilandia");
INSERT INTO Paises VALUES ("Sudáfrica");
INSERT INTO Paises VALUES ("Sudán");
INSERT INTO Paises VALUES ("Sudán del Sur");
INSERT INTO Paises VALUES ("Suecia");
INSERT INTO Paises VALUES ("Suiza");
INSERT INTO Paises VALUES ("Surinam");
INSERT INTO Paises VALUES ("Tailandia");
INSERT INTO Paises VALUES ("Tanzania");
INSERT INTO Paises VALUES ("Tayikistán");
INSERT INTO Paises VALUES ("Timor Oriental");
INSERT INTO Paises VALUES ("Togo");
INSERT INTO Paises VALUES ("Tonga");
INSERT INTO Paises VALUES ("Trinidad y Tobago");
INSERT INTO Paises VALUES ("Túnez");
INSERT INTO Paises VALUES ("Turkmenistán");
INSERT INTO Paises VALUES ("Turquía");
INSERT INTO Paises VALUES ("Tuvalu");
INSERT INTO Paises VALUES ("Ucrania");
INSERT INTO Paises VALUES ("Uganda");
INSERT INTO Paises VALUES ("Uruguay");
INSERT INTO Paises VALUES ("Uzbekistán");
INSERT INTO Paises VALUES ("Vanuatu");
INSERT INTO Paises VALUES ("Ciudad del Vaticano");
INSERT INTO Paises VALUES ("Venezuela");
INSERT INTO Paises VALUES ("Vietnam");
INSERT INTO Paises VALUES ("Yemen");
INSERT INTO Paises VALUES ("Yibuti");
INSERT INTO Paises VALUES ("Zambia");
INSERT INTO Paises VALUES ("Zimbabue");